services:
  auth_service:
    build:
      context: .
      dockerfile: app/api/v1/auth/Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - supabase_api

  agents_service:
    build:
      context: .
      dockerfile: app/api/v1/agents/Dockerfile
    env_file:
      - .env
    ports:
      - "8002:8000"
    depends_on:
      - supabase_api

  tools_service:
    build:
      context: .
      dockerfile: app/api/v1/tools/Dockerfile
    env_file:
      - .env
    ports:
      - "8003:8000"
    depends_on:
      - supabase_api

  nl_agents_service:
    build:
      context: .
      dockerfile: app/api/v1/nl_agents/Dockerfile
    env_file:
      - .env
    ports:
      - "8004:8000"
    depends_on:
      - supabase_api

  run_service:
    build:
      context: .
      dockerfile: app/api/v1/run/Dockerfile
    env_file:
      - .env
    ports:
      - "8005:8000"
    depends_on:
      - supabase_api

  langflow_ide:
    image: langflowai/langflow:latest
    env_file:
      - .env
    ports:
      - "7860:7860"
    depends_on:
      - supabase_api

volumes:
  supa_db_data: {}
