services:
  supabase_db:
    image: supabase/postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - supa_db_data:/var/lib/postgresql/data

  supabase_api:
    image: postgrest/postgrest:latest
    depends_on:
      - supabase_db
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@supabase_db:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
    ports:
      - "3000:3000"

  auth_service:
    build:
      context: .
      dockerfile: app/api/v1/auth/Dockerfile
    env_file:
      - .env
    environment:
      SUPABASE_URL: http://supabase_api:3000
    ports:
      - "8001:8000"
    depends_on:
      - supabase_api

  agents_service:
    build:
      context: .
      dockerfile: app/api/v1/agents/Dockerfile
    env_file:
      - .env
    environment:
      SUPABASE_URL: http://supabase_api:3000
    ports:
      - "8002:8000"
    depends_on:
      - supabase_api

  tools_service:
    build:
      context: .
      dockerfile: app/api/v1/tools/Dockerfile
    env_file:
      - .env
    environment:
      SUPABASE_URL: http://supabase_api:3000
    ports:
      - "8003:8000"
    depends_on:
      - supabase_api

  nl_agents_service:
    build:
      context: .
      dockerfile: app/api/v1/nl_agents/Dockerfile
    env_file:
      - .env
    environment:
      SUPABASE_URL: http://supabase_api:3000
    ports:
      - "8004:8000"
    depends_on:
      - supabase_api

  run_service:
    build:
      context: .
      dockerfile: app/api/v1/run/Dockerfile
    env_file:
      - .env
    environment:
      SUPABASE_URL: http://supabase_api:3000
    ports:
      - "8005:8000"
    depends_on:
      - supabase_api

  langflow_ide:
    image: langflowai/langflow:latest
    env_file:
      - .env
    environment:
      SUPABASE_URL: http://supabase_api:3000
    ports:
      - "7860:7860"
    depends_on:
      - supabase_api

volumes:
  supa_db_data: {}
