services:
  auth_service:
    extends:
      file: auth_service/docker-compose.dev.yml
      service: auth_service_dev

  agent_management_service:
    extends:
      file: agent_management_service/docker-compose.dev.yml
      service: agent_management_service_dev

  tool_registry_service:
    extends:
      file: tool_registry_service/docker-compose.dev.yml
      service: tool_registry_service_dev

  agent_deployment_service:
    extends:
      file: agent_deployment_service/docker-compose.dev.yml
      service: agent_deployment_service_dev
    volumes:
      # Gives container control of Docker engine
      - /var/run/docker.sock:/var/run/docker.sock
      # Gives container gcloud credentials
      - ~/.config/gcloud:/root/.config/gcloud
      # Gives container Docker's authentication config, allowing it to push to GCR
      - ~/.docker:/root/.docker

  conversation_service:
    extends:
      file: conversation_service/docker-compose.dev.yml
      service: conversation_service_dev

  # langflow_ide:
  #   image: langflowai/langflow:latest
  #   ports:
  #     - "7860:7860"
  #   env_file: .env
  #   environment:
  #     # This connects Langflow to the local Supabase Postgres instance
  #     LANGFLOW_DATABASE_URL: "postgresql://postgres:postgres@supabase_db_kgents:5432/postgres"
  #   networks:
  #     - kgents_network
  #     - supabase_network_kgents

networks:
  kgents_network:
    name: kgents_network
    driver: bridge
  supabase_network_kgents:
    external: true
    # The actual network name as created by Supabase CLI
