# nl_agents_service/docker-compose.dev.yml
services:
  nl_agents_service_dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./tests:/app/tests
    env_file:
      - ../.env # Load from the root .env file
    networks:
      - kgents_network
      - supabase_network_kgents # Connect to Supabase network from root compose

networks:
  kgents_network:
    name: kgents_network
    driver: bridge
  supabase_network_kgents:
    external: true
