"""Initial schema

Revision ID: 0258f662b012
Revises: 
Create Date: 2025-08-05 09:06:50.865812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0258f662b012'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='The ID of the agent being deployed, from the Agent Management Service.'),
    sa.Column('agent_version_id', sa.UUID(), nullable=False, comment='The specific version of the agent being deployed.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='The ID of the user who owns this deployment.'),
    sa.Column('status', sa.Enum('PENDING', 'DEPLOYING', 'RUNNING', 'FAILED', 'STOPPED', name='deployment_status_enum'), nullable=False, comment='The current status of the deployment lifecycle.'),
    sa.Column('endpoint_url', sa.Text(), nullable=True, comment='The URL where the deployed agent can be accessed once it is running.'),
    sa.Column('deployment_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Platform-specific metadata, e.g., Kubernetes pod name, container ID, etc.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Stores any error messages if the deployment fails.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_agent_id'), 'deployments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_deployments_agent_version_id'), 'deployments', ['agent_version_id'], unique=False)
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_index(op.f('ix_deployments_user_id'), 'deployments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_user_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_agent_version_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_agent_id'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
