# auth_service/docker-compose.dev.yml
services:
  auth_service_dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      # Mount the service's source code for hot-reloading
      - ./src:/app/src
      # Mount the shared code as an editable package
      - ../shared:/shared
    env_file:
      - ./.env.dev # Load development environment variables
    environment:
      # Pass these variables to the container for the entrypoint script
      - SERVICE_MODULE=auth_service
      - AUTH_SERVICE_POSTGRES_HOST=supabase_db_kgents
      - AUTH_SERVICE_POSTGRES_PORT=5432
      # Configure Python to find the shared package and auth_service module
      - PYTHONPATH=/app/src:/app:/shared:$PYTHONPATH
    networks:
      - kgents_network
      - supabase_network_kgents # Connect to Supabase network from root compose
