# tool_registry_service/docker-compose.dev.yml
services:
  tool_registry_service_dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./tests:/app/tests
      - ./scripts:/app/scripts
    env_file:
      - ./.env.dev # Load from the root .env file
    environment:
      # Pass these variables to the container for the entrypoint script
      - TOOL_REGISTRY_SERVICE_POSTGRES_HOST=supabase_db_kgents
      - TOOL_REGISTRY_SERVICE_POSTGRES_PORT=5432
    networks:
      - kgents_network
      - supabase_network_kgents # Connect to Supabase network from root compose

networks:
  kgents_network:
    name: kgents_network
    driver: bridge
  supabase_network_kgents:
    external: true
