"""Add metadata column to tools

Revision ID: f67d8a35f8da
Revises: 23bfef8c82e1
Create Date: 2025-08-11 08:27:36.172880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f67d8a35f8da"
down_revision: Union[str, None] = "23bfef8c82e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tools",
        sa.Column(
            "metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tools", "metadata")
    # ### end Alembic commands ###
