"""Initial schema

Revision ID: 2e3418e9ef1b
Revises: 
Create Date: 2025-08-10 13:12:38.445659

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e3418e9ef1b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="agentstatus"),
            nullable=False,
        ),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("active_version_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_version_id"],
            ["agent_versions.id"],
            name="fk_agent_active_version_id",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_id"), "agents", ["id"], unique=False)
    op.create_index(
        op.f("ix_agents_user_id"), "agents", ["user_id"], unique=False
    )
    op.create_table(
        "agent_versions",
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("config_snapshot", sa.JSON(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_versions_agent_id"),
        "agent_versions",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_versions_id"), "agent_versions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_versions_user_id"),
        "agent_versions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_versions_version_number"),
        "agent_versions",
        ["version_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_agent_versions_version_number"), table_name="agent_versions"
    )
    op.drop_index(
        op.f("ix_agent_versions_user_id"), table_name="agent_versions"
    )
    op.drop_index(op.f("ix_agent_versions_id"), table_name="agent_versions")
    op.drop_index(
        op.f("ix_agent_versions_agent_id"), table_name="agent_versions"
    )
    op.drop_table("agent_versions")
    op.drop_index(op.f("ix_agents_user_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_id"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
