name: Build Agent Docker Image
run-name: "Agent Deploy ${{ github.event.inputs.deployment_id }}"

on:
  workflow_dispatch:
    inputs:
      deployment_id:
        description: 'Deployment ID'
        required: true
        type: string
      image_tag:
        description: 'Full image tag (e.g., us-central1-docker.pkg.dev/PROJECT/REPO/IMAGE:TAG)'
        required: true
        type: string
      build_context:
        description: 'Base64 encoded tar.gz of build context'
        required: true
        type: string
      build_context_url:
        description: 'Optional HTTPS URL to a tar.gz build context (preferred for large contexts)'
        required: false
        type: string
      service_name:
        description: 'Cloud Run service name (optional)'
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # For Workload Identity Federation
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Extract build context
        run: |
          set -euo pipefail
          if [ -n "${{ github.event.inputs.build_context_url }}" ]; then
            echo "Downloading build context from URL..."
            URL="${{ github.event.inputs.build_context_url }}"
            # Add GitHub auth headers only for GitHub domains
            if echo "$URL" | grep -Eq '^https://(api\.github\.com|uploads\.github\.com|raw\.githubusercontent\.com|github\.com)/'; then
              echo "Using GitHub token for authenticated download"
              curl -fL --retry 3 --retry-delay 2 \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/octet-stream" \
                "$URL" -o build_context.tar.gz
            else
              curl -fL --retry 3 --retry-delay 2 "$URL" -o build_context.tar.gz
            fi
          else
            echo "Decoding base64 build context from input..."
            echo "${{ github.event.inputs.build_context }}" | base64 -d > build_context.tar.gz
          fi
          mkdir -p build_context
          tar -xzf build_context.tar.gz -C build_context
          ls -la build_context/
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: build_context
          platforms: linux/amd64
          push: true
          tags: ${{ github.event.inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify image exists in Artifact Registry
        run: |
          set -euo pipefail
          IMAGE_TAG="${{ github.event.inputs.image_tag }}"
          PROJECT_ID="kgents"
          REGION="us-central1"
          echo "Verifying image exists: $IMAGE_TAG"
          for i in 1 2 3 4 5; do
            if gcloud artifacts docker images describe "$IMAGE_TAG" --project "$PROJECT_ID" --location "$REGION" >/dev/null 2>&1; then
              echo "Image found in GAR."
              exit 0
            fi
            echo "Image not found yet, retrying in 5s... ($i/5)"
            sleep 5
          done
          echo "Image not found in GAR after retries"
          exit 1
      
      - name: Deploy to Cloud Run
        if: success()
        run: |
          SERVICE_NAME="${{ github.event.inputs.service_name }}"
          IMAGE_TAG="${{ github.event.inputs.image_tag }}"
          
          # Extract project ID correctly (it's always 'kgents' in our case)
          # Image format: us-central1-docker.pkg.dev/kgents/kgents-images/agent-runtime-xxx:latest
          PROJECT_ID="kgents"
          
          # Extract service name from image tag if not provided
          if [ -z "$SERVICE_NAME" ]; then
            SERVICE_NAME=$(echo "$IMAGE_TAG" | cut -d'/' -f4 | cut -d':' -f1)
          fi
          
          echo "Deploying service: $SERVICE_NAME"
          echo "Using image: $IMAGE_TAG"
          echo "Project ID: $PROJECT_ID"
          
          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE_TAG" \
            --platform managed \
            --region us-central1 \
            --port 8080 \
            --allow-unauthenticated \
            --project "$PROJECT_ID" \
            --set-env-vars "LANGFLOW_BACKEND_ONLY=true,LANGFLOW_OPEN_BROWSER=false,LANGFLOW_HOST=0.0.0.0" \
            --timeout 900 \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 1 \
            --format json > deployment.json
          
          echo "Deployment completed successfully!"
          echo "Service URL: $(jq -r '.status.url' deployment.json)"
      
      - name: Notify deployment service
        run: |
          echo "Build completed for deployment ${{ github.event.inputs.deployment_id }}"
          # Optional: Send webhook back to deployment service
          # curl -X POST ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}/build-complete \
          #   -H "Content-Type: application/json" \
          #   -d '{"deployment_id": "${{ github.event.inputs.deployment_id }}", "status": "success", "image": "${{ github.event.inputs.image_tag }}"}'
